#!/usr/bin/env python3
"""Generate the test PDFs in this directory.

Hand-built rather than borrowed, so they are unambiguously ours to redistribute, and
byte-reproducible: no timestamps or random IDs, so re-running is a no-op.

Standard library only, base-14 fonts only -- the modules are built with Poppler's "generic"
font configuration and have no system font access.

Usage: python3 tests/fixtures/make_fixtures.py
"""

import pathlib
import zlib

HERE = pathlib.Path(__file__).resolve().parent


def escape(text: str) -> str:
    """Escape a string for a PDF literal string."""
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def text_block(lines, x, y, size=12, leading=16, font="F1"):
    """Content-stream operators drawing `lines` from (x, y)."""
    out = ["BT", f"/{font} {size} Tf", f"{leading} TL", f"1 0 0 1 {x} {y} Tm"]
    for i, line in enumerate(lines):
        if i:
            out.append("T*")
        out.append(f"({escape(line)}) Tj")
    out.append("ET")
    return "\n".join(out)


def build_pdf(pages, compress=False):
    """Assemble a minimal PDF from a list of content streams.

    Fixed object layout: 1 = Catalog, 2 = Pages, 3 = Helvetica, then Page/Contents per page.
    """
    objects = {}

    page_ids = [4 + 2 * i for i in range(len(pages))]
    kids = " ".join(f"{pid} 0 R" for pid in page_ids)

    objects[1] = b"<< /Type /Catalog /Pages 2 0 R >>"
    objects[2] = (
        f"<< /Type /Pages /Count {len(pages)} /Kids [{kids}] >>".encode("ascii")
    )
    objects[3] = (
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
        b"/Encoding /WinAnsiEncoding >>"
    )

    for i, content in enumerate(pages):
        page_id = page_ids[i]
        contents_id = page_id + 1
        objects[page_id] = (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Resources << /Font << /F1 3 0 R >> >> "
            f"/Contents {contents_id} 0 R >>".encode("ascii")
        )
        raw = content.encode("ascii")
        if compress:
            # Exercises zlib: Poppler must inflate this to see any text.
            body = zlib.compress(raw, 9)
            stream_dict = f"<< /Length {len(body)} /Filter /FlateDecode >>"
        else:
            body = raw
            stream_dict = f"<< /Length {len(body)} >>"
        objects[contents_id] = (
            stream_dict.encode("ascii") + b"\nstream\n" + body + b"\nendstream"
        )

    # Classic cross-reference table.
    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = {}
    for num in sorted(objects):
        offsets[num] = len(out)
        out += f"{num} 0 obj\n".encode("ascii") + objects[num] + b"\nendobj\n"

    xref_pos = len(out)
    count = max(objects) + 1
    out += f"xref\n0 {count}\n".encode("ascii")
    out += b"0000000000 65535 f \n"
    for num in range(1, count):
        out += f"{offsets[num]:010d} 00000 n \n".encode("ascii")
    # No /ID: it would be either random or fake.
    out += (
        f"trailer\n<< /Size {count} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n"
    ).encode("ascii")
    return bytes(out)


def fixtures():
    simple = text_block(
        [
            "Hello from poppler-wasi.",
            "This PDF is generated by make_fixtures.py.",
            "It uses only the base-14 Helvetica font.",
        ],
        72,
        700,
    )

    # Far enough apart that -layout reconstructs them side by side while default mode reads
    # them as separate blocks, which is what makes the -layout golden meaningful.
    left = text_block(
        ["Left column one", "Left column two", "Left column three"], 72, 700
    )
    right = text_block(
        ["Right column one", "Right column two", "Right column three"], 340, 700
    )
    layout = left + "\n" + right

    page_one = text_block(["Page one of two.", "Alpha bravo charlie."], 72, 700)
    page_two = text_block(["Page two of two.", "Delta echo foxtrot."], 72, 700)

    return {
        "simple.pdf": build_pdf([simple]),
        "layout.pdf": build_pdf([layout]),
        # simple.pdf's text, Flate-compressed: a broken zlib shows up as empty extraction.
        "flate.pdf": build_pdf([simple], compress=True),
        "multipage.pdf": build_pdf([page_one, page_two]),
    }


def main():
    for name, data in sorted(fixtures().items()):
        path = HERE / name
        existing = path.read_bytes() if path.exists() else None
        if existing == data:
            print(f"unchanged {name} ({len(data)} bytes)")
            continue
        path.write_bytes(data)
        print(f"{'updated' if existing else 'wrote'} {name} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
